"""profile migrations

Revision ID: e4b6b7fa764a
Revises: b92c30291e3b
Create Date: 2022-05-17 20:33:50.616595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b6b7fa764a'
down_revision = 'b92c30291e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###
